language: elixir
notifications:
  email: false
elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
otp_release:
  - 19.3
  - 20.3
  - 21.0
  - 22.0
  - 23.1
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 21.0
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 20.3

env: MIX_ENV=test
sudo: false # faster builds

before_script:
  - mix deps.get
script:
  - mix coveralls.travis
  - mix test
after_script:
  - "MIX_ENV=docs mix deps.get && MIX_ENV=docs mix inch.report"
