language: elixir
notifications:
  email: false
elixir:
  - 1.3.0
  - 1.4.2
  - 1.9.1
otp_release:
  - 20.0
  - 21.0
  - 22.0
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis
  - mix test
after_script:
  - "MIX_ENV=docs mix deps.get && MIX_ENV=docs mix inch.report"
