name: Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.x
          elixir-version: 1.15
      - name: Publish package to hex.pm
        uses: cucumber/action-publish-hex@v1.0.0
        with:
          hex-api-key: ${{ secrets.HEX_API_KEY }}
